[package]
name = "nrfcat"
version = "0.1.0"
authors = ["Matthias Oelmann (octopus) <mao@viergleicheins.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap-parser = "0.9.3"
ansi_term = "0.12.1"